# Generated by Django 5.2.4 on 2025-08-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignschedule',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignschedule',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
