# Generated by Django 5.2.4 on 2025-08-14 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_campaignschedule_end_date_and_more'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignschedule',
            name='crontab_schedule',
        ),
        migrations.AddField(
            model_name='campaignschedule',
            name='crontab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.crontabschedule'),
        ),
    ]
